### PR TITLE
Simple avail type

### PR DESCRIPTION
**Pull request by meyerjrr**
Adds new api for QueryEntitlement which lists an deduplicated list of target : role pairs.

The original QueryAvailabilties has been left in and is used for cli queries. See here for updates to cli 
https://github.com/common-fate/cli/pull/52

### CODE REVIEW

**Review by chrnorm — APPROVED** [review]
Looks good. A note on naming, our docs and codebase currently refer to an [Entitlement](https://docs.commonfate.io/setup/glossary#entitlement) as a combination of Principal + Target + Role. The API you've introduced uses Entitlement as Target + Role (no Principal).

I think we should implement the API you've introduced, and update our docs and call the Principal+Target+Role combo an "Assignment" instead of "Entitlement" to avoid confusion.

**Comment by chrnorm** [comment]
We should also look to deprecate the other Availabilities API eventually

**Comment by JoshuaWilkes** [comment]
We should standardise on naming for list APIs seems we are using both Queryx and Listx interchangeably. Is there a standard practice we should adopt here for grpc?

**Comment by chrnorm** [comment]
There isn't a standard AFAIK - agreed though we should ourselves standardise on one or the other. I have been using `QueryX` for endpoints that could take filters as parameters and `ListX` for endpoints that don't, but this may be confusing in the long term

**Review by JoshuaWilkes — APPROVED** [review]

**Pull request merged**
